-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.493.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/19/2013 5:29:55 PM
-- Server version: 5.1.69
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO voicemail.prompts(id, name) VALUES
(1, 'Invalid_Request');
INSERT INTO voicemail.prompts(id, name) VALUES
(2, 'User_Not_Exist');
INSERT INTO voicemail.prompts(id, name) VALUES
(3, 'User_Greeting');
INSERT INTO voicemail.prompts(id, name) VALUES
(4, 'User_Name_recording');
INSERT INTO voicemail.prompts(id, name) VALUES
(5, 'User_Leave_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(6, 'Message_Saved');
INSERT INTO voicemail.prompts(id, name) VALUES
(7, 'Invalid_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(8, 'User_Vm_Access');
INSERT INTO voicemail.prompts(id, name) VALUES
(9, 'Help_Menu');
INSERT INTO voicemail.prompts(id, name) VALUES
(10, 'VM_Summary');
INSERT INTO voicemail.prompts(id, name) VALUES
(11, 'VM_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(12, 'First_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(13, 'Last_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(14, 'Next_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(15, 'No_More_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(16, 'Post_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(17, 'Still_There');
INSERT INTO voicemail.prompts(id, name) VALUES
(18, 'Goodbye');
INSERT INTO voicemail.prompts(id, name) VALUES
(19, 'Still_There_VM_Get_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(20, 'Login_Welcome_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(21, 'Login_Invalid_Mailbox');
INSERT INTO voicemail.prompts(id, name) VALUES
(22, 'Login_Input_Password_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(23, 'Login_Invalid_Password');
INSERT INTO voicemail.prompts(id, name) VALUES
(24, 'Login_Logged_In');
INSERT INTO voicemail.prompts(id, name) VALUES
(25, 'RSF_Input_Record_Now');
INSERT INTO voicemail.prompts(id, name) VALUES
(26, 'RSF_Amenu_Record');
INSERT INTO voicemail.prompts(id, name) VALUES
(27, 'RSF_Message_Deleted');
INSERT INTO voicemail.prompts(id, name) VALUES
(28, 'Login_Still_There_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(29, 'RSF_Approved_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(30, 'RSF_Create_Forward_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(31, 'RSF_Record_Still_There_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(32, 'RSF_Forward_Still_There_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(33, 'RSF_Delivered_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(34, 'RSF_Cancelled_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(35, 'Send_Input_List_Now');
INSERT INTO voicemail.prompts(id, name) VALUES
(36, 'Send_Still_There_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(37, 'Send_Invalid_Mailbox_List');
INSERT INTO voicemail.prompts(id, name) VALUES
(38, 'Send_Approved_Delivered_Count');
INSERT INTO voicemail.prompts(id, name) VALUES
(39, 'Send_Removed_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(40, 'Send_Added_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(41, 'Personal_Greeting_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(42, 'Personal_Greeting_Still_There_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(43, 'Greetings_Busy_Is_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(44, 'Greetings_Temp_Is_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(45, 'Greetings_Unavailable_Is_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(46, 'Greetings_Not_Set_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(47, 'Greetings_Record_Menu');
INSERT INTO voicemail.prompts(id, name) VALUES
(48, 'Greetings_Busy_Record_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(49, 'Greetings_Unavail_Record_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(50, 'Greetings_Temp_Record_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(51, 'Greetings_Approved_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(52, 'Greetings_Busy_Not_Set');
INSERT INTO voicemail.prompts(id, name) VALUES
(53, 'Greetigns_Unavail_Not_Set');
INSERT INTO voicemail.prompts(id, name) VALUES
(54, 'Greetings_Temp_Not_Set');
INSERT INTO voicemail.prompts(id, name) VALUES
(55, 'Personal_Options_Menu');
INSERT INTO voicemail.prompts(id, name) VALUES
(56, 'Personal_Options_Still_There_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(57, 'AML_Menu_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(58, 'AML_Record_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(59, 'AML_Record_List_Name');
INSERT INTO voicemail.prompts(id, name) VALUES
(60, 'AML_Enter_Key_Code');
INSERT INTO voicemail.prompts(id, name) VALUES
(61, 'Password_Enter_New');
INSERT INTO voicemail.prompts(id, name) VALUES
(62, 'Password_No_Match');
INSERT INTO voicemail.prompts(id, name) VALUES
(63, 'Password_Re_Enter_New');
INSERT INTO voicemail.prompts(id, name) VALUES
(64, 'Password_Changed_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(65, 'Record_Name_Name_Is');
INSERT INTO voicemail.prompts(id, name) VALUES
(66, 'Record_Name_Record');
INSERT INTO voicemail.prompts(id, name) VALUES
(67, 'Scan_Menu_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(68, 'Scan_Still_There_Message');
INSERT INTO voicemail.prompts(id, name) VALUES
(69, 'Invalid_Option');
INSERT INTO voicemail.prompts(id, name) VALUES
(70, 'Internal_Access_Welcome');
