-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.493.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/19/2013 5:29:54 PM
-- Server version: 5.1.69
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(1, 1, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-invalid.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(2, 2, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-invalidmailbox.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(3, 3, 1, 4, '', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(4, 4, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-theperson.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(5, 4, 2, 3, '', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(6, 4, 3, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-isunavail.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(7, 5, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-theperson.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(8, 6, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-savedm.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(9, 7, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-invalid.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(10, 8, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-activity.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(11, 5, 2, 2, 'Extension', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(12, 5, 3, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-isunavail.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(13, 5, 4, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-leavemessage.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(14, 9, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-activity-help.wav', 2, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(15, 10, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-youhave.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(16, 10, 2, 2, 'Unread-Count', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(17, 10, 3, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-and.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(18, 10, 4, 2, 'Read-Count', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(19, 11, 1, 2, 'VM-Header', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(20, 11, 2, 5, 'VM', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(21, 12, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-first.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(23, 13, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-last.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(24, 14, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-message.wav', 2, 1);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(25, 14, 2, 2, 'sayNum', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(26, 15, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-nomoremessages.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(27, 12, 2, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-message.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(28, 12, 3, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-received.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(29, 16, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-getrespond.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(30, 17, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-stillthere.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(31, 18, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-goodbye.wav', 10, NULL);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(32, 19, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-getrespond-help.wav', 2, 2);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(33, 20, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-welcome', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(34, 20, 2, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-mailbox-now', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(35, 21, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-invalidmailbox', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(36, 22, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-password-now', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(37, 23, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-invalidpassword', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(38, 24, 1, 4, '', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(39, 24, 1, 99, 'file://var/lib/asterisk/sounds/en/macp/vm-tempgreetingactive', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(40, 25, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-recordnow', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(41, 26, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-amenu-record', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(42, 27, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-deleted', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(43, 28, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-activity-help', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(44, 29, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-approved', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(45, 30, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-emenu-createforward', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(46, 31, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-amenu-record-help', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(47, 32, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-emenu-createforward-help', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(48, 33, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-delivered', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(49, 34, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-cancelled', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(50, 35, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-listnow', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(51, 36, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-amenu-listmailboxlist', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(52, 37, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-invalidmailboxlist', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(53, 38, 1, 2, 'Destination-Count', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(54, 38, 2, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-delivered', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(55, 39, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-removed', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(56, 40, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-added', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(57, 41, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-greetings', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(58, 42, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-greetings-help', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(59, 43, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-busyis', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(60, 44, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-tempis', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(61, 45, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-unavailis', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(62, 46, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-notset', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(63, 47, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-amenu-record', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(64, 48, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-recordbusy', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(65, 49, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-recordunavail', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(66, 50, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-recordtemp', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(67, 51, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-approved', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(68, 52, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-busyis', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(69, 52, 2, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-notset', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(70, 53, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-unavailis', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(71, 53, 2, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-notset', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(72, 54, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-tempis', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(73, 54, 2, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-netset', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(74, 55, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-poptions', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(75, 56, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-tmenu-poptions-help', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(76, 57, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-smenu-lists', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(77, 58, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-amenu-record', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(78, 59, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-listname', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(79, 60, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-listnum', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(80, 61, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-newpassword', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(81, 62, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-passwordnomatch', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(82, 63, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-verifypassword', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(83, 64, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-act-passwordchanged', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(84, 65, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-nameis', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(85, 66, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-input-recordname', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(86, 67, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-smenu-scan', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(87, 68, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-smenu-scan-help', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(88, 69, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-invalidoption', 10, 10);
INSERT INTO voicemail.prompt_details(id, prompt_id, sequence_number, prompt_type, path, delay_before, delay_after) VALUES
(89, 70, 1, 1, 'file://var/lib/asterisk/sounds/en/macp/mc-message-welcome', 10, 10);
